language: java

matrix:
    include:
        - os: linux
          jdk: openjdk8
        - os: linux
          jdk: openjdk11
          env: JACOCO='-PenableJaCoCo'
        - os: linux
          jdk: openjdk14
        - os: linux
          jdk: openjdk-ea
        - os: osx
          jdk: openjdk11
    allow_failures:
        - jdk: openjdk14
        - jdk: openjdk-ea  

script:
  - ./gradlew -version
  - ./gradlew build jacocoTestReport --stacktrace

# Do not store unnecessary files from Gradle dependency cache
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Store Gradle dependency cache and Gradle Wrapper files for next execution
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
 
 # Upload JaCoCo report to codecov   
after_success:
  - test "$COVERAGE" = "true" && bash <(curl -s https://codecov.io/bash) || true
    
